server:
  port: 9003
spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/myconfig/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka