server:
  port: 8081
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    prefer-ip-address: true
zuul:
  prefix: /api
  routes:
    #    provider: /user/**
    #    provider2: /order/**
    customerRelationship: /customerRelationship/**  #简化配置
    ignored-services: "*"
#    ignored-patterns: /**/user/**
  #    provider1:
  #     path: /user/**
  #     serverId: provider


#  myroute1:
#    path: /user/**
#    serverId: cr
#  myroute2:
#    path: /order/**
#    serverId: cr2
