#server:
#  port: 9091
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9001/eureka
#  instance:
#    prefer-ip-address: true
#spring:
#  application:
#    name: CR
#    datasource:
#      type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
#info:
#  app.name: xwk
#  author: xwk
#
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#spring.datasource.url: jdbc:mysql://localhost:3306/jxc?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&userSSL=false&serverTimezone=GMT%2B8
#spring.datasource.username: root
#spring.datasource.password: 123456
#
#mybatis-plus.mapper-locations: classpath:/mapper/*.xml
#mybatis-plus.type-aliases-package: com.example.microservice2.entity
#mybatis-plus.configuration.map-underscore-to-camel-case: true
#
